### PR TITLE
Update to GNOME 3.38

### PR DESCRIPTION
**Pull request by Eonfge**
Update to latest runtime, which is based on Free Desktop 20.08

### CODE REVIEW

**Comment by antenore** [comment]
Thanks @Eonfge 
I'll test it ASAP and merge

**Comment by Eonfge** [comment]
I've run a few basic checks, but I'll give it some more attention tomorrow at the office. Ironically, I have nothing to remote into from where I am right now.

The reason I'm currently looking into Remmina, is because I intend to cover it in a Fedora Magazine article. I want to use this Flatpak as to explain people how to recompile applications, and how to validate hashes. It will be part of a multi-part article on the web-of-trust and validating binaries, so I wanted to do my preparation before submitting it for an editorial pass.

**Comment by antenore** [comment]
Yes, please, if I choose 'automatic colour depth' (codecs negotiation) it fails with this error:

```
[22:20:14:184] [2:12] [ERROR][com.freerdp.codec] - Failed to initialize libav parser
[22:20:14:184] [2:12] [ERROR][com.freerdp.core.codecs] - Failed to create h264 codec context
``` 

I'm wondering if it's caused by the ffmpeg update? I'm not sure as it's freerdp that raise this error.

**Comment by antenore** [comment]
And I confirm that with the previous version works

**Comment by Eonfge** [comment]
I don't have any RDP-connected servers under my wing, so I can't test that. VNC seems fine though. 

Perhaps roll back the ffmpeg-full upgrade? Or just wait with this release until you have it worked out in freerdp. The current GNOME Runtime will remain supported for the next 6 months, so you have some time to work with

**Comment by antenore** [comment]
If GNOME doesn't depends on that specific version of ffmpeg-full, yes, I think it is tyhe best solution.

If it's not an hard dependency, do you mind updating this PR? Otherwise I'll update it but in some days.

Thanks again!

**Comment by antenore** [comment]
Awesome! 
If you need anything let me know, and when it'll be published I'd like to buy one issue.

**Comment by Eonfge** [comment]
3.38 Seems to work fine for me here at the office. Still only SSH and VNC connections, but tunneling and so seems fine.

**Comment by Eonfge** [comment]
@antenore So, good to go? I'll make an issue for the ffmpeg package after we can finish this

**Comment by antenore** [comment]
Yes, it's good for me.
Merging and thanks a lot!

**Comment by antenore** [comment]
@Eonfge I've to temporary rollback this as the RDP plugin is missing, so it wasn't a ffmpeg issue, but the gnome framework.

I'll try to understand why, but the error message, starting remmina is:

```
Failed to load plugin: /app/lib/remmina/plugins/remmina-plugin-rdp.so.
Error: libdav1d.so.2: cannot open shared object file: No such file or directory
```

**Comment by Eonfge** [comment]
Damn. Shame we didn't detect that. They've likely removed it from the base FreeDesktop runtime, which is a bit odd. It can be bundled with ffmpeg, so they could have moved it from the base 20.08 runtime to the 20.80 ffmpeg extension. Pure speculation, but we'll have to look into that.

Alternatively, we can include it ourself:
https://code.videolan.org/videolan/dav1d

**Comment by antenore** [comment]
@alexlarsson May I have a little help on this?

Switching from org.gnome.Platform 3.36 to 3.38 breaks the FreeRDP dependencies, in fact starting Remimna show this error message:

```
Failed to load plugin: /app/lib/remmina/plugins/remmina-plugin-rdp.so.
Error: libdav1d.so.2: cannot open shared object file: No such file or directory
``` 

The flatpak build doesn't fail, so we detect this only at runtime.

I've troubles figuring out if we should report this to the freedesktop team, use another extension (we are using org.freedesktop.Platform.ffmpeg-full) or add dav1d our self and building ffmpeg  instead of using the extension.

Thanks in advance and sorry to bother you!!!

**Pull request merged**
