### PR TITLE
Rollback phodav

### PR DESCRIPTION
**Pull request by Eonfge**
Ensure it doesn't auto-update to 3.0

### CODE REVIEW

**Comment by antenore** [comment]
Thank you!!! Do you mind doing the same for libsoup? 
I don't have a PC for one week

**Comment by Eonfge** [comment]
Is libsoup a direct dependency? 

I checked all the dependencies and this was the one that was giving me issues. With this package rolled back, I can run Remmina right now

Screenshot from 2022-07-15 14-02-37

**Comment by Eonfge** [comment]
Screenshot from 2022-07-15 14-28-14

:ok_hand:

**Comment by Eonfge** [comment]
Best wishes from my employer. Your tool is invaluable to me for managing our servers, so I got the thumbs up to aid you right now.

**Comment by antenore** [comment]
You are awesome, and your employer too ;-)

**Pull request merged**
