### PR TITLE
update libssh (security update)

### PR DESCRIPTION
**Pull request by dgcampea**
should have been batched with the last PR

### CODE REVIEW

**Comment by antenore** [comment]
Thanks!

Testing

BTW @dgcampea do you want to join us on gitlab to apply the same modification ? Or do you want we apply these fixes by ourself?

**Comment by antenore** [comment]
https://gitlab.com/Remmina/Remmina/tree/master/flatpak

Just in case ;-)

**Comment by dgcampea** [comment]
@antenore https://gitlab.com/Remmina/Remmina/merge_requests/1993

**Comment by antenore** [comment]
Thanks! Merged over there, the flatpak works and I'm merging this as well.

**Pull request merged**
