### PR TITLE
Update to GNOME 3.38 and org.freedesktop.Platform.ffmpeg-full 20.08

### LINKED ISSUE #38: Update the runtime to Gnome 3.38
Please, update the runtime to org.gnome.Platform/x86_64/3.38
Thanks

### PR DESCRIPTION
**Pull request by antenore**
- Fixes #38
- Use ffmpeg as an extension
- FFmpeg-full, due to possible legal stubbornness in the USA, it can't be
  downloaded automatically

Signed-off-by: Antenore Gatta <antenore@simbiosi.org>

### CODE REVIEW

**Comment by antenore** [comment]
@Eonfge @codingepaduli any comments are welcome

Due to USA law potential issues, I've forced ffmpeg-full to not be downloaded automatically.

The users will have to install it with `flatpak install org.freedesktop.Platform.ffmpeg-full`

**Comment by antenore** [comment]
Looks good, I'm merging and we will see for fixes eventually

**Comment by Eonfge** [comment]
Are you sure this works with the latest librdp? I remember that you had to revert two weeks ago because of librdp related issues?

As for the copyright, I know the pain. I also did it for Lollypop: I make ffmpeg-full an optional add-on, and I compiled the ugly plugins against the add-on so that if the user adds ffmpeg-full, he can use it to play .wma and .rma audio files.

**Comment by antenore** [comment]
> Are you sure this works with the latest librdp? I remember that you had to revert two weeks ago because of librdp related issues?
> 
> As for the copyright, I know the pain. I also did it for Lollypop: I make ffmpeg-full an optional add-on, and I compiled the ugly plugins against the add-on so that if the user adds ffmpeg-full, he can use it to play .wma and .rma audio files.

I've tested both, locally and the test build.

I'll try later the published one, but the change I've done looks good.

I've changed from add-extension-build to add-extension and, bizarre, it works...

**Comment by Eonfge** [comment]
>  add-extension-build to add-extension

We have two versions? I totally missed that! According to the [manual](https://docs.flatpak.org/en/latest/flatpak-builder-command-reference.html), `add-extension-build` doesn't even exist and it should have been `add-build-extensions`... So not sure why it worked earlier.

**Pull request merged**
