### PR TITLE
Update gnome runtime

### PR DESCRIPTION
**Pull request by iavael**

### CODE REVIEW

**Comment by iavael** [comment]
@flathubbot rebuild

**Comment by iavael** [comment]
@flathubbot /rebuild

**Comment by antenore** [comment]
Thank you @iavael

**Comment by antenore** [comment]
I've tried to not compiling the examples, but:

1. The client examples are built anyway (can you revert that commit? It seems I cannot)
2. The problem seems more related to ffmpeg

Unfortunately I don't have much time to debug this :-( :-(  , I'm very sorry

I'd try, just for the sake of a test, to build libvnc using the master branch. I say this because they have applied some fixes related to ffmpeg, like https://github.com/LibVNC/libvncserver/pull/520 

If the test goes well, the hard thing will be to find the patches that eventually solve the problem.

Maybe @bk138 do you have some ideas?

**Comment by bk138** [comment]
@antenore you could configure the build to leave out the examples, see https://github.com/LibVNC/libvncserver/blob/master/CMakeLists.txt#L62

**Comment by antenore** [comment]
> @antenore you could configure the build to leave out the examples, see https://github.com/LibVNC/libvncserver/blob/master/CMakeLists.txt#L62

That is what I've done, but it still builds the client_examples.

But I think the problem is not really there, as we are trying to use the latest ffmpeg extension, it seems is something related to some changes in ffmpeg itself

**Comment by bk138** [comment]
@antenore you're right, this will not woth with libvncserver 0.9.13 as it was added with https://github.com/LibVNC/libvncserver/commit/0b8990784a81823eecc9089263ac1966d17bf399

**Comment by bk138** [comment]
@antenore FYI LibVNCServer 0.9.14 will hopefully get released this year, so you can change this afterwards...

**Comment by iavael** [comment]
@antenore lgtm

**Comment by antenore** [comment]
I cannot merge it. It seems I've to do a merge request in your branch with my changes.

Do you mind submitting a new one with all the changes and one commit?

**Comment by antenore** [comment]
@TingPing @nedrichards Sorry to bother I need your help.

In this PR I've added some commits myself, but when I try to merge, even forcing I get this error:

```
$ git push --force origin master                                                                                  1 ↵
Enter passphrase for key '/home/tmow/.ssh/id_rsa':
Enumerating objects: 40, done.
Counting objects: 100% (38/38), done.
Delta compression using up to 12 threads
Compressing objects: 100% (32/32), done.
Writing objects: 100% (32/32), 5.25 KiB | 5.25 MiB/s, done.
Total 32 (delta 22), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (22/22), completed with 4 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Changes must be made through a pull request.
To github.com:flathub/org.remmina.Remmina.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'github.com:flathub/org.remmina.Remmina.git'
```

**Comment by iavael** [comment]
Squashed all commits in one

**Comment by antenore** [comment]
I still have the same error as before https://github.com/flathub/org.remmina.Remmina/pull/164#issuecomment-1357508199

@TingPing @nedrichards I need your help please

**Comment by TingPing** [comment]
@antenore You can't force push. Rebase your commits (`git pull --rebase origin master`) then push.

**Comment by antenore** [comment]
Thank you @TingPing

**Pull request merged**
