### PR TITLE
Remove unnecessary portal permission

### PR DESCRIPTION
**Pull request by bbhtt**
Fixes https://github.com/flathub/org.remmina.Remmina/issues/223

### CODE REVIEW

**Comment by myheroyuki** [comment]
Looks good, thanks!

**Comment by bbhtt** [comment]
@myheroyuki The build is failing please see https://buildbot.flathub.org/#/builders/31/builds/8684

**Comment by myheroyuki** [comment]
Hmm, interesting. It seems that `appstream-missing-developer-name` appeared in the validate step of the past several builds, but in those cases it was just a warning, not an error. Now that it has been updated to an error it makes the build fail.

**Comment by bbhtt** [comment]
Yes it was promoted to an error last night, that was after the test build happened. So it didn't affect the test build but affected the merge build

**Comment by myheroyuki** [comment]
Ah, that explains it. So if we add a developer name it should fix the issue. Doesn't sound too difficult .

**Comment by bbhtt** [comment]
Yes, https://docs.flathub.org/docs/for-app-authors/appdata-guidelines/#name-summary-and-developer-name

**Pull request merged**
